title: Just the Docs Template
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://iuliarebecalupas.github.io/iuliarebecalupas.github.io-sql-journey

aux_links:
  Template Repository: https://github.com/iuliarebecalupas/iuliarebecalupas.github.io-sql-journey
